@extends('layouts.admin')

@section('title', 'Semua Lowongan | Admin KerjaLokal')
@section('portal_title', 'Semua lowongan')
@section('portal_description', 'Lihat lowongan dari seluruh mitra beserta identitas akun penerbit dan status rekrutmennya.')

@section('content')
    <form method="GET" class="mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-[1fr_220px_auto] dark:border-slate-800 dark:bg-slate-900"><div><label for="q" class="portal-label">Judul atau nama usaha</label><input id="q" name="q" value="{{ request('q') }}" class="portal-input" placeholder="Cari lowongan atau UMKM"></div><div><label for="status" class="portal-label">Status</label><select id="status" name="status" class="portal-input"><option value="">Semua status</option><option value="open" @selected(request('status') === 'open')>Dibuka</option><option value="closed" @selected(request('status') === 'closed')>Ditutup</option></select></div><div class="flex items-end gap-2"><button class="portal-button-primary">Cari</button><a href="{{ route('admin.jobs.index') }}" class="portal-button-secondary">Reset</a></div></form>
    <div class="portal-table-shell overflow-x-auto"><table class="portal-table"><thead><tr><th>Lowongan</th><th>Akun mitra</th><th>Upah dan jam</th><th>Status</th><th>Pelamar</th><th class="text-right">Aksi</th></tr></thead><tbody>@forelse($jobs as $job)<tr><td><a href="{{ route('admin.jobs.show', $job) }}" class="font-bold text-slate-950 hover:text-brand-700 dark:text-white">{{ $job->title }}</a><span class="mt-1 block text-xs text-slate-500">{{ $job->category->name }} · {{ $job->location }}</span></td><td><span class="font-semibold">{{ $job->employer->business_name }}</span><span class="mt-1 block text-xs text-slate-500">{{ $job->employer->name }} · {{ $job->employer->email }}</span></td><td><span class="font-semibold">Rp {{ number_format($job->salary_amount, 0, ',', '.') }}</span><span class="mt-1 block text-xs text-slate-500">{{ $job->work_hours_per_day }} jam / hari</span></td><td><span class="portal-badge {{ $job->status === 'open' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300' }}">{{ $job->status === 'open' ? 'Dibuka' : 'Ditutup' }}</span></td><td>{{ $job->applications_count }}</td><td><div class="flex justify-end gap-2"><a href="{{ route('admin.jobs.show', $job) }}" class="portal-button-secondary">Detail</a><form action="{{ route('admin.jobs.status', $job) }}" method="POST">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $job->status === 'open' ? 'closed' : 'open' }}"><button class="portal-button-secondary">{{ $job->status === 'open' ? 'Tutup' : 'Buka' }}</button></form></div></td></tr>@empty<tr><td colspan="6" class="py-12 text-center text-slate-500">Tidak ada lowongan yang sesuai.</td></tr>@endforelse</tbody></table></div>
    <div class="mt-7">{{ $jobs->links() }}</div>
@endsection
