@extends('layouts.admin')

@section('title', $job->title.' | Admin KerjaLokal')
@section('portal_title', $job->title)
@section('portal_description', 'Detail lowongan, akun mitra penerbit, keterampilan, dan seluruh pelamar terkait.')
@section('portal_actions')<a href="{{ route('admin.jobs.index') }}" class="portal-button-secondary"><span class="material-symbols-outlined text-[18px]">arrow_back</span>Kembali</a><form action="{{ route('admin.jobs.status', $job) }}" method="POST">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $job->status === 'open' ? 'closed' : 'open' }}"><button class="portal-button-primary">{{ $job->status === 'open' ? 'Tutup lowongan' : 'Buka kembali' }}</button></form>@endsection

@section('content')
    <div class="grid gap-6 lg:grid-cols-[1fr_340px]">
        <div class="space-y-6"><section class="portal-panel p-6"><div class="flex flex-wrap items-center gap-2"><span class="portal-badge bg-brand-50 text-brand-700 dark:bg-brand-950 dark:text-brand-300">{{ $job->category->name }}</span><span class="portal-badge {{ $job->status === 'open' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300' }}">{{ $job->status === 'open' ? 'Dibuka' : 'Ditutup' }}</span></div><dl class="mt-6 grid gap-4 sm:grid-cols-3"><div><dt class="text-xs text-slate-400">Lokasi</dt><dd class="mt-1 font-bold">{{ $job->location }}</dd></div><div><dt class="text-xs text-slate-400">Upah</dt><dd class="mt-1 font-bold">Rp {{ number_format($job->salary_amount, 0, ',', '.') }} / {{ $job->salary_type === 'monthly' ? 'bulan' : 'hari' }}</dd></div><div><dt class="text-xs text-slate-400">Jam kerja</dt><dd class="mt-1 font-bold">{{ $job->work_hours_per_day }} jam / hari</dd></div></dl><div class="mt-6 border-t border-slate-100 pt-6 dark:border-slate-800"><h2 class="font-bold">Deskripsi</h2><p class="mt-3 whitespace-pre-line text-sm leading-7 text-slate-600 dark:text-slate-300">{{ $job->description }}</p></div><div class="mt-6 flex flex-wrap gap-2">@foreach($job->skills as $skill)<span class="rounded-lg bg-slate-100 px-3 py-1.5 text-xs font-bold dark:bg-slate-800">{{ $skill->name }}</span>@endforeach</div></section>
            <section class="portal-panel overflow-hidden"><div class="portal-panel-header"><div><h2 class="font-bold">Pelamar terkait</h2><p class="text-xs text-slate-500">{{ $job->applications_count }} lamaran pada lowongan ini.</p></div></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($job->applications as $application)<div class="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-bold">{{ $application->user->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $application->user->email }}{{ $application->user->phone ? ' · '.$application->user->phone : '' }} · Status {{ ucfirst($application->status) }}</p></div><a href="{{ route('admin.applications.resume', $application) }}" class="portal-button-secondary"><span class="material-symbols-outlined text-[18px]">download</span>Resume</a></div>@empty<div class="p-10 text-center text-sm text-slate-500">Belum ada pelamar.</div>@endforelse</div></section></div>
        <aside class="portal-panel h-fit p-6"><div class="grid h-12 w-12 place-items-center rounded-2xl bg-brand-50 text-brand-700 dark:bg-brand-950 dark:text-brand-300"><span class="material-symbols-outlined">storefront</span></div><h2 class="mt-5 text-lg font-bold">Akun mitra penerbit</h2><dl class="mt-5 space-y-4 text-sm"><div><dt class="text-xs text-slate-400">Nama usaha</dt><dd class="mt-1 font-bold">{{ $job->employer->business_name }}</dd></div><div><dt class="text-xs text-slate-400">Penanggung jawab</dt><dd class="mt-1 font-semibold">{{ $job->employer->name }}</dd></div><div><dt class="text-xs text-slate-400">Email</dt><dd class="mt-1 break-all font-semibold">{{ $job->employer->email }}</dd></div><div><dt class="text-xs text-slate-400">Telepon</dt><dd class="mt-1 font-semibold">{{ $job->employer->phone ?: 'Belum diisi' }}</dd></div><div><dt class="text-xs text-slate-400">Terdaftar</dt><dd class="mt-1 font-semibold">{{ $job->employer->created_at->translatedFormat('d F Y') }}</dd></div></dl></aside>
    </div>
@endsection
