@extends('layouts.app')

@section('title', 'Profil Saya | KerjaLokal')

@section('content')
    <div class="grid gap-6 lg:grid-cols-[340px_1fr]">
        <aside class="rounded-3xl bg-brand-950 p-6 text-white lg:self-start" data-reveal><div class="grid h-16 w-16 place-items-center rounded-2xl bg-white/10 text-2xl font-bold">{{ str($user->name)->substr(0, 1)->upper() }}</div><h1 class="mt-5 text-2xl font-bold">{{ $user->name }}</h1><p class="mt-1 text-sm text-brand-200">Pencari kerja</p><dl class="mt-8 space-y-4 border-t border-white/10 pt-6 text-sm"><div><dt class="text-xs text-brand-300">Email</dt><dd class="mt-1 break-all font-semibold">{{ $user->email }}</dd></div><div><dt class="text-xs text-brand-300">Nomor telepon</dt><dd class="mt-1 font-semibold">{{ $user->phone ?: 'Belum diisi' }}</dd></div><div><dt class="text-xs text-brand-300">Bergabung</dt><dd class="mt-1 font-semibold">{{ $user->created_at->translatedFormat('d F Y') }}</dd></div></dl></aside>
        <div class="space-y-5">
            <section class="grid gap-4 sm:grid-cols-2" data-reveal><div class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><span class="material-symbols-outlined text-brand-600">assignment</span><strong class="mt-4 block text-3xl">{{ $user->job_applications_count }}</strong><span class="text-sm text-slate-500">lamaran diajukan</span></div><div class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><span class="material-symbols-outlined text-brand-600">verified_user</span><strong class="mt-4 block text-3xl">Aktif</strong><span class="text-sm text-slate-500">status akun</span></div></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900" data-reveal><h2 class="text-lg font-bold">Akses cepat</h2><div class="mt-5 grid gap-3 sm:grid-cols-2"><a href="{{ route('applications.index') }}" class="flex items-center justify-between rounded-xl bg-slate-50 p-4 font-bold transition hover:bg-brand-50 hover:text-brand-700 dark:bg-slate-950 dark:hover:bg-brand-950"><span class="flex items-center gap-2"><span class="material-symbols-outlined">assignment</span>Riwayat lamaran</span><span class="material-symbols-outlined text-[18px]">arrow_forward</span></a><a href="{{ route('jobs.index') }}" class="flex items-center justify-between rounded-xl bg-slate-50 p-4 font-bold transition hover:bg-brand-50 hover:text-brand-700 dark:bg-slate-950 dark:hover:bg-brand-950"><span class="flex items-center gap-2"><span class="material-symbols-outlined">search</span>Cari lowongan</span><span class="material-symbols-outlined text-[18px]">arrow_forward</span></a></div></section>
            <section class="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200" data-reveal><strong>Privasi berkas:</strong> Resume hanya disimpan ketika Anda melamar. Berkas hanya dapat diakses oleh mitra pemilik lowongan dan administrator.</section>
        </div>
    </div>
@endsection
