@extends('layouts.admin')

@section('title', 'Pengguna | Admin KerjaLokal')
@section('portal_title', 'Pengguna sistem')
@section('portal_description', 'Tinjau akun pencari kerja, mitra UMKM, dan administrator beserta aktivitas utamanya.')

@section('content')
    <form method="GET" class="mb-6 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:flex-row sm:items-end dark:border-slate-800 dark:bg-slate-900"><div class="w-full sm:max-w-xs"><label for="role" class="portal-label">Filter role</label><select id="role" name="role" class="portal-input"><option value="">Semua role</option><option value="jobseeker" @selected(request('role') === 'jobseeker')>Pencari kerja</option><option value="employer" @selected(request('role') === 'employer')>Mitra UMKM</option><option value="admin" @selected(request('role') === 'admin')>Administrator</option></select></div><button class="portal-button-primary">Terapkan</button><a href="{{ route('admin.users.index') }}" class="portal-button-secondary">Reset</a></form>
    <div class="portal-table-shell overflow-x-auto"><table class="portal-table"><thead><tr><th>Pengguna</th><th>Role</th><th>Usaha</th><th>Aktivitas</th><th>Terdaftar</th><th class="text-right">Aksi</th></tr></thead><tbody>@forelse($users as $user)<tr><td><span class="font-bold">{{ $user->name }}</span><span class="mt-1 block text-xs text-slate-500">{{ $user->email }}{{ $user->phone ? ' · '.$user->phone : '' }}</span></td><td><span class="portal-badge bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200">{{ match($user->role) {'jobseeker' => 'Pencari kerja', 'employer' => 'Mitra UMKM', default => 'Admin'} }}</span></td><td>{{ $user->business_name ?: 'Tidak berlaku' }}</td><td><span class="text-xs text-slate-500">{{ $user->jobs_count }} lowongan · {{ $user->job_applications_count }} lamaran</span></td><td>{{ $user->created_at->translatedFormat('d M Y') }}</td><td><div class="flex justify-end">@if(!$user->hasRole('admin'))<form action="{{ route('admin.users.destroy', $user) }}" method="POST">@csrf @method('DELETE')<button class="portal-button-secondary text-rose-600"><span class="material-symbols-outlined text-[18px]">delete</span>Hapus</button></form>@else<span class="text-xs text-slate-400">Dilindungi</span>@endif</div></td></tr>@empty<tr><td colspan="6" class="py-12 text-center text-slate-500">Tidak ada pengguna.</td></tr>@endforelse</tbody></table></div>
    <div class="mt-7">{{ $users->links() }}</div>
@endsection
